//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RegisterTable
    {
        public long Account_Number { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Account_Holdername { get; set; }
        [Required(ErrorMessage = "EmailAddress is required")]
        [EmailAddress]
        public string Email_id { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        [Required(ErrorMessage = "Mobile_Number is required")]
        public Nullable<long> Mobile_Number { get; set; }
        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }

        public string LoginErrorMsg { get; set; }
    }
}
